In [1]:
import numpy as np

In [2]:
# create numpy array from list
arr = np.array([1, 5, 5, 6])
arr_2d = np.array([[1, 5, 5, 6]])
print(arr, type(arr), arr.dtype, arr.shape)
print(arr_2d, arr_2d.shape)

[1 5 5 6] <class 'numpy.ndarray'> int64 (4,)
[[1 5 5 6]] (1, 4)


In [3]:
# 2d array
arr2d = np.array([[1, 3, 4], [3, 4, 2], [5, 7, 4], [3, 5, 1]])
print(arr2d, type(arr2d), arr2d.dtype, arr2d.shape)

[[1 3 4]
 [3 4 2]
 [5 7 4]
 [3 5 1]] <class 'numpy.ndarray'> int64 (4, 3)


In [4]:
# prefill array
arr1 = np.zeros((3, 5), dtype="int64") #prefill with zeros
print(arr1, arr1.shape)

arr2 = np.ones((4, )) #prefill with ones
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 5) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye((3)) #prefill with identical matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) #range element
print(arr5, arr5.shape)

arr6 = np.linspace(0, 100, 3, dtype ="int64") #evenly space array
print(arr6, arr6.shape)

arr7 = np.array([np.arange(0, 11, 2), np.arange(10, 21, 2), np.arange(20, 31, 2)])
print(arr7, arr7.shape)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] (3, 5)
[1. 1. 1. 1.] (4,)
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  0  50 100] (3,)
[[ 0  2  4  6  8 10]
 [10 12 14 16 18 20]
 [20 22 24 26 28 30]] (3, 6)


In [5]:
#Properties
arr = np.array([[1, 3, 5, 4], [2, 5, 6, 3], [3, 5, 1, 7]])
print(arr.shape) #dimension = m x n
print(arr.size) # total no. of element
print(arr.dtype)
print(arr.ndim) # no. of dimensions

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 4)
12
int64
2
[[1. 3. 5. 4.]
 [2. 5. 6. 3.]
 [3. 5. 1. 7.]] float64


In [6]:
# Reshaping Array
arr = np.array([[3, 5 ,7], [2, 5, 4]])
print(arr, arr.shape)

reshaped_arr = arr.reshape((3, 2))
print(reshaped_arr, reshaped_arr.shape)

# flatten array
flattened_arr = arr.flatten() #flatten 2D => 1D
print(flattened_arr, flattened_arr.shape)

[[3 5 7]
 [2 5 4]] (2, 3)
[[3 5]
 [7 2]
 [5 4]] (3, 2)
[3 5 7 2 5 4] (6,)


In [7]:
# Indexing on Array
arr = np.array([[3, 5 ,7], [2, 5, 4], [3, 5, 2]])
print(arr[0, 2])

#Fancy Indexing
row = [0, 2, 1]
col = [1, 2, 2]
print(arr[row, col])

#Boolean Indexing
print(arr[arr<5]) #print element less than 5
print(arr[arr%2 == 0]) #print even elements
print(arr[arr%2 != 0]) #print odd elements

7
[5 2 4]
[3 2 4 3 2]
[2 4 2]
[3 5 7 5 3 5]


In [8]:
#Slicing on 2D Array
arr = np.array([[3, 5 ,7],
                [2, 5, 4],
                [3, 5, 2]])

print(arr[0:2, 0:2])
print(arr[::2, ::2])
print(arr[1:, 1:])
print(arr[0:2, 1:2])
print(arr[:, 2])

[[3 5]
 [2 5]]
[[3 7]
 [3 2]]
[[5 4]
 [5 2]]
[[5]
 [5]]
[7 4 2]


In [9]:
# List create copy and npArray create view in slice
print(f"Example of list's copy")
list = [1, 3, 5, 4, 6]
sub_list = list[1:4]
print(sub_list)
sub_list[1] = 200
print(sub_list)
print(list)

   #VS
print(f"Example of array's view")
arr = np.array([1, 3, 2, 5, 8])
sub_arr = arr[1:4]
print(sub_arr)
sub_arr[1] = 300
print(sub_arr)
print(arr)

# How to copy in npArray
print(f"Example: how to create copy in array")
arr = np.array([1, 3, 2, 5, 8])
sub_arr = arr[1:4].copy()
print(sub_arr)
sub_arr[1] = 300
print(sub_arr)
print(arr)

Example of list's copy
[3, 5, 4]
[3, 200, 4]
[1, 3, 5, 4, 6]
Example of array's view
[3 2 5]
[  3 300   5]
[  1   3 300   5   8]
Example: how to create copy in array
[3 2 5]
[  3 300   5]
[1 3 2 5 8]


In [10]:
# Numpy Data Type
arr = np.array([3, 5, 6])
print(arr, arr.dtype)
arr2 = np.array([3, 5, 7.2])
print(arr2, arr2.dtype)
arr3 = np.array([3, 5, 7.2, "nine"])
print(arr3, arr3.dtype)
arr7 = np.array([4, "prime", 6.34, {4, 6, 3}])
print(arr7, arr7.dtype)

#Complex number
arr4 = np.array([-7+6j])
arr5 = np.array([5-9j])
print(arr4 + arr5)

num = np.array([4.56])
print(num.dtype)
arr6 = np.array([4-3j])
print(arr6, arr6.dtype)

[3 5 6] int64
[3.  5.  7.2] float64
['3' '5' '7.2' 'nine'] <U32
[4 'prime' 6.34 {3, 4, 6}] object
[-2.-3.j]
float64
[4.-3.j] complex128


In [11]:
# Vectorization
# Vectorization means performing operations on entire arrays at once instead of using loops (like for loops).
arr = np.array([1, 3, 5, 6, 7])
arr2 = np.array([2, 4, 5, 6, 7])

print(arr**2)
print(arr + 10)
print(arr + arr2)

[ 1  9 25 36 49]
[11 13 15 16 17]
[ 3  7 10 12 14]


In [12]:
# Broadcasting
# Broadcasting is a mechanism in NumPy that allows you to perform operations on arrays of different shapes by automatically “expanding” the smaller one to match the larger one.
arr = np.array([1, 2, 5, 6, 7]) #shape => 1 x 5
arr2 = np.array([[1, 3, 4, 5, 6], [2, 5, 6, 7, 8]]) #shape => 2 x 5
arr3 = np.array([[2], [2]]) #shape => 2 x 1

print(arr + arr2) 
print(arr2 + arr3)

[[ 2  5  9 11 13]
 [ 3  7 11 13 15]]
[[ 3  5  6  7  8]
 [ 4  7  8  9 10]]
